@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0


class Student {
#name: String
#grade: String
#group: String
-NICKNAME: String
+addStudentToList(Student): void
+getStudentDetails(): ArrayList
+getStudentGrade(String studentName): String
+setGrade(String studentName, String grade): void

}

@enduml